# Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,jaccard_score,f1_score,log_loss,confusion_matrix
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

# Load data

In [2]:
hr_df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
hr_df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [3]:
hr_df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [4]:
hr_df.shape

(1470, 35)

In [5]:
hr_df[hr_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 35 columns]

# Data Preprocessing

In [6]:
x = hr_df.iloc[:,:].values
x= np.delete(x,1,axis=1)
print(x[:10,:])

[[41 'Travel_Rarely' 1102 'Sales' 1 2 'Life Sciences' 1 1 2 'Female' 94 3
  2 'Sales Executive' 4 'Single' 5993 19479 8 'Y' 'Yes' 11 3 1 80 0 8 0 1
  6 4 0 5]
 [49 'Travel_Frequently' 279 'Research & Development' 8 1 'Life Sciences'
  1 2 3 'Male' 61 2 2 'Research Scientist' 2 'Married' 5130 24907 1 'Y'
  'No' 23 4 4 80 1 10 3 3 10 7 1 7]
 [37 'Travel_Rarely' 1373 'Research & Development' 2 2 'Other' 1 4 4
  'Male' 92 2 1 'Laboratory Technician' 3 'Single' 2090 2396 6 'Y' 'Yes'
  15 3 2 80 0 7 3 3 0 0 0 0]
 [33 'Travel_Frequently' 1392 'Research & Development' 3 4
  'Life Sciences' 1 5 4 'Female' 56 3 1 'Research Scientist' 3 'Married'
  2909 23159 1 'Y' 'Yes' 11 3 3 80 0 8 3 3 8 7 3 0]
 [27 'Travel_Rarely' 591 'Research & Development' 2 1 'Medical' 1 7 1
  'Male' 40 3 1 'Laboratory Technician' 2 'Married' 3468 16632 9 'Y' 'No'
  12 3 4 80 1 6 3 3 2 2 2 2]
 [32 'Travel_Frequently' 1005 'Research & Development' 2 2
  'Life Sciences' 1 8 4 'Male' 79 3 1 'Laboratory Technician' 4 'Single'

In [7]:
y = hr_df.Attrition
y.head()

0    Yes
1     No
2    Yes
3     No
4     No
Name: Attrition, dtype: object

In [8]:
# applying encoding
y = LabelEncoder().fit_transform(y)
print(y[:10])

[1 0 1 0 0 0 0 0 0 0]


In [9]:
x[:,10]=LabelEncoder().fit_transform(x[:,10])
x[:,20]=LabelEncoder().fit_transform(x[:,20])
x[:,21]=LabelEncoder().fit_transform(x[:,21])
print(x[:10,:])

[[41 'Travel_Rarely' 1102 'Sales' 1 2 'Life Sciences' 1 1 2 0 94 3 2
  'Sales Executive' 4 'Single' 5993 19479 8 0 1 11 3 1 80 0 8 0 1 6 4 0 5]
 [49 'Travel_Frequently' 279 'Research & Development' 8 1 'Life Sciences'
  1 2 3 1 61 2 2 'Research Scientist' 2 'Married' 5130 24907 1 0 0 23 4 4
  80 1 10 3 3 10 7 1 7]
 [37 'Travel_Rarely' 1373 'Research & Development' 2 2 'Other' 1 4 4 1 92
  2 1 'Laboratory Technician' 3 'Single' 2090 2396 6 0 1 15 3 2 80 0 7 3
  3 0 0 0 0]
 [33 'Travel_Frequently' 1392 'Research & Development' 3 4
  'Life Sciences' 1 5 4 0 56 3 1 'Research Scientist' 3 'Married' 2909
  23159 1 0 1 11 3 3 80 0 8 3 3 8 7 3 0]
 [27 'Travel_Rarely' 591 'Research & Development' 2 1 'Medical' 1 7 1 1
  40 3 1 'Laboratory Technician' 2 'Married' 3468 16632 9 0 0 12 3 4 80 1
  6 3 3 2 2 2 2]
 [32 'Travel_Frequently' 1005 'Research & Development' 2 2
  'Life Sciences' 1 8 4 1 79 3 1 'Laboratory Technician' 4 'Single' 3068
  11864 0 0 0 13 3 3 80 0 8 2 2 7 7 3 6]
 [59 'Travel_Rare

In [10]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,3,6,14,16])],remainder='passthrough') # Apply tranformation to change education to binary vector
x = np.array(ct.fit_transform(x))
print(x[:10,:])

[[0.0 0.0 1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 0.0 0.0 0.0 1.0 41 1102 1 2 1 1 2 0 94 3 2 4 5993 19479 8 0 1
  11 3 1 80 0 8 0 1 6 4 0 5]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 1.0 0.0 49 279 8 1 1 2 3 1 61 2 2 2 5130 24907 1 0 0 23
  4 4 80 1 10 3 3 10 7 1 7]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 1.0 37 1373 2 2 1 4 4 1 92 2 1 3 2090 2396 6 0 1 15
  3 2 80 0 7 3 3 0 0 0 0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 0.0 0.0 0.0 1.0 0.0 33 1392 3 4 1 5 4 0 56 3 1 3 2909 23159 1 0 1
  11 3 3 80 0 8 3 3 8 7 3 0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 1.0 0.0 27 591 2 1 1 7 1 1 40 3 1 2 3468 16632 9 0 0 12
  3 4 80 1 6 3 3 2 2 2 2]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 0.0 0.0 0.0 1.0 32 1005 2 2 1 8 4 1 79 3 1

# Test and Train data

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [12]:
# Normalize the data
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Build and Evaluate Model

In [13]:
model = LogisticRegression(solver='lbfgs')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(y_pred, y_test)))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy 88.21%
[[364  13]
 [ 39  25]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.93       377
           1       0.66      0.39      0.49        64

    accuracy                           0.88       441
   macro avg       0.78      0.68      0.71       441
weighted avg       0.87      0.88      0.87       441



In [14]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("Accuracy {0:.2f}%".format(100*accuracy_score(y_pred, y_test)))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy 86.85%
[[375   2]
 [ 56   8]]
              precision    recall  f1-score   support

           0       0.87      0.99      0.93       377
           1       0.80      0.12      0.22        64

    accuracy                           0.87       441
   macro avg       0.84      0.56      0.57       441
weighted avg       0.86      0.87      0.82       441

